[package]
name = "game-2048"
version = "0.1.0"
authors = ["sta8071"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
device_query = "0.2.4"
rand = "*"